### ISSUE TITLE
Malformed NFT's might cause an error on metadataTask.run 

### ISSUE THREAD

**Issue by mavarazy** [metaplex-foundation/js#110]
Some nfts returned by `findAllByMintList` might nor follow the Metaplex standard and return an error:
```
metaplex
    .nfts()
    .findAllByMintList(tokens.map((token) => new PublicKey(token.mint)));
```

In my case this was for [MSRMcoVyrFxnSgo5uXwone5SKcGhT1KEJMFEkMEWf9L](https://explorer.solana.com/address/MSRMcoVyrFxnSgo5uXwone5SKcGhT1KEJMFEkMEWf9L/metadata)

```
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/anton/Development/snapi/forbex-nxr/node_modules/node-fetch/lib/index.js:1327:9)
    at /Users/anton/Development/snapi/forbex-nxr/node_modules/node-fetch/lib/index.js:1440:19
    at new Promise (<anonymous>)
    at Object.fetch (/Users/anton/Development/snapi/forbex-nxr/node_modules/node-fetch/lib/index.js:1437:9)
    at Object.fetch [as default] (/Users/anton/Development/snapi/forbex-nxr/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at BundlrStorageDriver.downloadJson (/Users/anton/Development/snapi/forbex-nxr/node_modules/@metaplex-foundation/js-next/src/types/StorageDriver.ts:28:33)
    at callback (/Users/anton/Development/snapi/forbex-nxr/node_modules/@metaplex-foundation/js-next/src/plugins/nftModule/useJsonMetadataTask.ts:10:31)
    at callback (/Users/anton/Development/snapi/forbex-nxr/node_modules/@metaplex-foundation/js-next/src/utils/useTask.ts:74:40)
    at Object.run (/Users/anton/Development/snapi/forbex-nxr/node_modules/@metaplex-foundation/js-next/src/utils/useDisposable.ts:43:36)
    at forceRun (/Users/anton/Development/snapi/forbex-nxr/node_modules/@metaplex-foundation/js-next/src/utils/useTask.ts:66:23)
```
I'm not sure If this is expected and should be handled by the client, or by the library.

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for raising this issue.

Aside from maybe a better error message, what sort of behaviour would you expect from this SDK?

**Comment by lorisleiva** [comment]
Hi there 👋 I'm closing this for now but feel free to open a new issue with more information on the matter and I'll look into it. Thank you. 🪴
