### ISSUE TITLE
instantSale Error

### ISSUE THREAD

**Issue by KarthikaPJAccubits** [metaplex-foundation/js#183]
I’m currently trying to use the @metaplex/js sdk to create the auction and then buying one of the editions for a fixed instant sale price. In final step “instantSale” I get the following error **“Error: Unable to find account:** …

MetaplexError: Unable to find account: CTXJV1fbNg6VmCAvCuDvQqEkSArnpa59NCsd7Ms6L8BP
    at ERROR_ACCOUNT_NOT_FOUND (/home/accubits/Mint_API_TS/node_modules/@metaplex-foundation/mpl-core/src/errors.ts:34:10)
    at Function.<anonymous> (/home/accubits/Mint_API_TS/node_modules/@metaplex-foundation/mpl-core/src/accounts/Account.ts:42:36)
    at Generator.next (<anonymous>)
    at fulfilled (/home/accubits/Mint_API_TS/node_modules/@metaplex-foundation/mpl-core/dist/src/accounts/Account.js:5:58)

**Comment by ShuklaSushant** [comment]
I hope you have created vault first then added NFt then create auction & auction manager & then set authority.. follow https://docs.metaplex.com/architecture/basic_flow#2-the-auction

**Comment by ShuklaSushant** [comment]
> nable to find acc

There are in total 11 transactions that happen on blockchain...i have found 9 out of 11 , still stuck on last 2 transactions

**Comment by ShuklaSushant** [comment]
i am analyzing all the transactions of instantsale , there are in total 11 transaction , i have found 9 of them
Need help in last 2
createExternalPriceAccount --> createVault --> addTokensToVault --> closeVault --> initAuction --> InitAuctionManagerV2 --> SetVaultAndAuctionAuthorities --> ValidateSafetyDepositBox --> StartAuction

I hope this flow will help anyone who is also trying to study instantSale

Still there are 2 more transactions that execute when we use metaplex UI, Can anyone help what to do after `StartAuction`

**Comment by nurav97** [comment]
@KarthikaPJAccubits can you post a sample code of how you implemented auction flow as i am stuck on it

**Comment by nurav97** [comment]
@ShuklaSushant i am getting custom error code 0x33 when running InitAuctionManagerV2 instruction can you help me as i am stuck on this from many days
