### ISSUE TITLE
ERROR_INVALID_OWNER

### ISSUE THREAD

**Issue by clibc** [metaplex-foundation/js#187]
**Describe the bug**
Given code produces this error :
```
(node:3532) UnhandledPromiseRejectionWarning: Error: Invalid owner
    at ERROR_INVALID_OWNER (W:\test_ts\node_modules\@metaplex-foundation\mpl-core\dist\src\errors.js:19:12)
    at new Metadata (W:\test_ts\node_modules\@metaplex-foundation\mpl-token-metadata\dist\src\accounts\Metadata.js:100:54)
    at Function.<anonymous> (W:\test_ts\node_modules\@metaplex-foundation\mpl-core\dist\src\accounts\Account.js:27:20)
    at Generator.next (<anonymous>)
    at fulfilled (W:\test_ts\node_modules\@metaplex-foundation\mpl-core\dist\src\accounts\Account.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Run this code 
```
import { Connection, programs } from '@metaplex/js';
const { metadata: { Metadata } } = programs;

const connection = new Connection('devnet');
const tokenPublicKey = 'GzFLQnbaLoth65T79vjXZRJBT8fqx3eD3Q8F31cmZHTu';

const run = async () => {
    const ownedMetadata = await Metadata.load(connection, tokenPublicKey);
    console.log(ownedMetadata);
};

run();
```

**Expected behavior**
I was expected to get metadata of token account

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by amurad77** [comment]
Qəliz məsələdir 'Yola ver'ə basın

**Comment by flatplate** [comment]
I have the same problem, can't query anything other than the given public key in the docs 🤔

**Comment by ali-ahari-hashemi** [comment]
Any updates with this? Running into the same issue.

**Comment by ali-ahari-hashemi** [comment]
Check out the issue here: https://github.com/metaplex-foundation/js/issues/39

Was using the wrong pubkey.

**Comment by clibc** [comment]
export async function GetMetadata(token_pubkey) {
    const mintPubkey = new PublicKey(token_pubkey);
    const tokenmetaPubkey = await Metadata.getPDA(mintPubkey);
    
    
    try {
        const tokenmeta = await Metadata.load(connection, tokenmetaPubkey);
        return tokenmeta;
    }
    catch {
        console.log("unable to find token metadata: " + token_pubkey);
        return undefined;
    }
}
