### ISSUE TITLE
Update creators error: Incorrect account owner

### ISSUE THREAD

**Issue by elliott-w** [metaplex-foundation/js#261]
I'mn trying to update a list of nfts to have a new secondary creator (the one with the 100% share). I don't think it's possible to update the first creator because I think the first creator is signed by the candy machine that created the nft? Anyway here's my code:

```ts
import { keypairIdentity, Metadata, Metaplex } from '@metaplex-foundation/js'
import { Connection, Keypair, PublicKey } from '@solana/web3.js'
import { program } from 'commander'
import { readFileSync, writeFileSync } from 'fs'

program
  .command('update_creators')
  .description('Updates the creator of all nfts')
  .requiredOption(
    '-i, --input-file <string>',
    'Json file, list of NFT mint details'
  )
  .requiredOption(
    '-o,  --output-file <string>',
    'Output file for NFT addresses that failed to update'
  )
  .requiredOption(
    '-k, --keypair-file <path>',
    `JSON file containing private key of token owner`,
    '.cache/creator-keypair.json'
  )
  .option('-r, --rpc <string>', 'JSON rpc api url', defaultRpc)
  .action(async ({ inputFile, outputFile, keypairFile, rpc }) => {
    const connection = new Connection(rpc)
    const metaplex = Metaplex.make(connection)
    const keypairFileContents = readFileSync(keypairFile, 'utf-8')
    const keypair = Keypair.fromSecretKey(
      Buffer.from(JSON.parse(keypairFileContents))
    )
    metaplex.use(keypairIdentity(keypair))

    const nftMintAddresses = JSON.parse(
      readFileSync(inputFile, 'utf-8')
    ) as string[]

    let nfts = (await metaplex
      .nfts()
      .findAllByMintList({
        mints: nftMintAddresses.map(mint => new PublicKey(mint)),
      })
      .run()) as Metadata[]

    const newCreator = new PublicKey(
      'CUAwUE5N3TdHHHyPTHb3E5mpnpQFiRF6BcY8kEvJakfS'
    )
    const failedNfts: any[] = []

    for (const nft of nfts) {
      try {
        console.dir(nft, { depth: null })
        const newNft = await metaplex
          .nfts()
          .update({
            nftOrSft: nft,
            creators: [
              nft.creators[0],
              {
                address: newCreator,
                share: 100,
                authority: keypair,
              },
            ],
          })
          .run()
        console.dir(newNft, { depth: null })
      } catch (e) {
        console.error(e)
        failedNfts.push(nft)
        process.exit()
      }
    }
    writeFileSync(outputFile, JSON.stringify(failedNfts))
  })
```
Note, the `metaplex.use()` keypair I'm using is the same wallet used to create the candy machine and has authority to update the nfts. I keep getting the following error:

```
ParsedProgramError [MetaplexError]: TokenMetadataProgram > Incorrect account owner
>> Source: Program > TokenMetadataProgram [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s]
>> Problem: The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error of code [57] that translates to "Incorrect account owner".
>> Solution: Check the error message provided by the program.

Caused By: IncorrectOwner: Incorrect account owner

    at RpcClient.parseProgramError (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\plugins\rpcModule\RpcClient.ts:302:9)
    at RpcClient.sendTransaction (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\plugins\rpcModule\RpcClient.ts:87:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RpcClient.sendAndConfirmTransaction (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\plugins\rpcModule\RpcClient.ts:117:23)
    at async TransactionBuilder.sendAndConfirm (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\utils\TransactionBuilder.ts:189:22)
    at async C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\utils\Task.ts:82:23
    at async Disposable.run (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\utils\Disposable.ts:34:14)
    at async Command.<anonymous> (C:\xampp\htdocs\sol-tools\src\cli.ts:263:24) {
  key: 'metaplex.errors.program.parsed_program_error',
  title: 'TokenMetadataProgram > Incorrect account owner',
  problem: 'The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error of code [57] that translates to "Incorrect account owner".',
  solution: 'Check the error message provided by the program.',
  source: 'program',
  sourceDetails: 'TokenMetadataProgram [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s]',
  cause: IncorrectOwner: Incorrect account owner
      at Object.errorResolver (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\plugins\nftModule\plugin.ts:70:16)
      at RpcClient.parseProgramError (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\plugins\rpcModule\RpcClient.ts:299:35)
      at RpcClient.sendTransaction (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\plugins\rpcModule\RpcClient.ts:87:18)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RpcClient.sendAndConfirmTransaction (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\plugins\rpcModule\RpcClient.ts:117:23)
      at async TransactionBuilder.sendAndConfirm (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\utils\TransactionBuilder.ts:189:22)
      at async C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\utils\Task.ts:82:23
      at async Disposable.run (C:\xampp\htdocs\sol-tools\node_modules\@metaplex-foundation\js\src\utils\Disposable.ts:34:14)
      at async Command.<anonymous> (C:\xampp\htdocs\sol-tools\src\cli.ts:263:24) {
    code: 57
  },
  logs: undefined,
  program: {
    name: 'TokenMetadataProgram',
    address: PublicKey {
      _bn: <BN: b7065b1e3d17c45389d527f6b04c3cd58b86c731aa0fdb549b6d1bc03f82946>
    },
    errorResolver: [Function: errorResolver],
    gpaResolver: [Function: gpaResolver]
  }
}
```

And here's one of the NFTs I'm trying to update:

https://solscan.io/token/3woKb11Ajs9VkzHhMNkiyX5za1bV3STBmSaDHoQgmBKp#metadata

Any help would be appreciated. Thanks!

**Comment by lorisleiva** [comment]
It looks like the Metadata account you're trying to update is not owned by the Token Metadata program.

See https://github.com/metaplex-foundation/metaplex-program-library/blob/58d10c46e66ca9d9c6288999ca9289c986587c7f/token-metadata/program/src/processor.rs#L326

Also, your update call is adding a new creator with 100% shares whilst the current `creators[0]` should also have 100% shares. Once you get past this error, the program will complain that your new creator array does not add up to 100%.

**Comment by elliott-w** [comment]
@lorisleiva 

> It looks like the Metadata account you're trying to update is not owned by the Token Metadata program.

Is that normal for NFTs minted via CMv2?

**Comment by elliott-w** [comment]
>  Unless it was a forked CMv2 program

No nothing like that, CM was made using the depecrated `candy-machine-v2-cli.ts`

> Have you tried with another NFT to be sure?

Yeah here's another one from the same candy machine:
https://solscan.io/token/YAPp4X629HnHLnpRf4cEWhUFEeiSx3uJQhi95nu65Em#metadata

If I do:
```
const nftMintAddresses = ['YAPp4X629HnHLnpRf4cEWhUFEeiSx3uJQhi95nu65Em']
```
still gives same `incorrect account owner` error.

> Also, your update call is adding a new creator

Could you please elaborate? I thought by specifying the creators property I'm replacing the old creators array with a new one?

**Comment by elliott-w** [comment]
I've messed up somewhere I'm sure of it 😅

> Which RPC and cluster are you using when running this update operation?

mainnet-beta, I've tried both my quiknode:
https://autumn-wispy-forest.solana-mainnet.quiknode.pro/9df0b2e72ee22da25d7be7cc97fb85656e938255
And genesysgo:
https://ssc-dao.genesysgo.net/

**Comment by lorisleiva** [comment]
Well, you seem to be doing everything properly so I'm not sure why you'd have this incorrect owner error.

I'll reopen this until we find out what's causing this issue.

**Comment by elliott-w** [comment]
Thanks, much appreciated

**Comment by elliott-w** [comment]
@lorisleiva can you recommend another way to update creators at this point?

**Comment by lorisleiva** [comment]
@elliott-w Sure, you can use the `@metaplex-foundation/mpl-token-metadata` library directly which is auto-generated from the Rust program. But the SDK delegates to that library so I'm not sure if that would make a difference.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm just going through all issues again today. and I was wondering if you'd find a solution to this issue.

I'm still confused as to why the update operation wouldn't work since what you're trying to achieve has been heavily tested on the SDK.

If you could provide a small repository for me to play with such that it's got the minimum amount of code required to reproduce the issue that'd be super helpful.

Thanks again for raising this.

**Comment by lorisleiva** [comment]
Closing this due to inactivity.

**Comment by numoonchld** [comment]
Seeing this error on my dApp when trying to update the URI for the `metadataJSON`

**Comment by sohrab-** [comment]
I don't know if I should revive this old thread but I think I know what's going on here.

The `address` field that comes back from `find*()` seems to be the metadata PDA, not the token. Then `update()` uses this to derive other stuff like metadata and edition, which most likely won't exist, and hence won't have the correct parent.

Here is a minimal example:

```typescript
const nfts = await metaplex.nfts().findAllByUpdateAuthority({
  updateAuthority: myAuthority.publicKey,
});
await metaplex
  .nfts()
  .update({
    nftOrSft: nfts[0],
    authority: myAuthority,
    newUpdateAuthority: myNewAuthority,
  })
```

Here is a devnet example:

* [Token mint transaction](https://solscan.io/tx/3cvHUcJV11wJrzgnDnguHQRijYkVGWBJmeSTY1YVYuyuEgTubanQPe4DvXtwpNbLL4H1mw2wnTbW8K9frSihPm3L?cluster=devnet)
* [Update NFT transaction](https://solscan.io/tx/5M96D4PY59pvJ6uU5J6SkvW3QtwqVhFYfnTJYquND2AUNY5ungbkymVV9g7bxLFSQm393LxBgXHqZUXhHWJkm64x?cluster=devnet) (I did two updates in the same transaction but consider the first one for this example)

This is what `find*()` returns for this NFT:

```
{
  model: 'metadata',
  address: Pda [PublicKey(6HuZcq6nWAGPmTpEfs2iRx6VE96o3hJsR5MHvyxnrPnr)] {
    _bn: <BN: 4e9f28f8a120445719d888baa86803ac85c1559295e927dc109f3223b91350d3>,
    bump: 255
  },
  mintAddress: PublicKey [PublicKey(DnkEX2cFszKxmAZqqgn8cXU8ts3QecMFnW4HHbEYcyHD)] {
    _bn: <BN: be04436806993280d6a9d49b657d1641a8ebe8f032bfcf0ad1f4acea8a2e3b94>
  },
  updateAuthorityAddress: PublicKey [PublicKey(9viqaqpquezaABFw7BAwTcFtAmkHECcJ4NyWBM5a2ZK1)] {
    _bn: <BN: 84a09592a9fe4d4642a9827cdfa823aec199d9cd7219b5e9e294a8fa7c62774c>
  },
  json: null,
  jsonLoaded: false,
  name: 'Bob #7',
  symbol: '',
  uri: 'https://something/7',
  isMutable: true,
  primarySaleHappened: false,
  sellerFeeBasisPoints: 250,
  editionNonce: 253,
  creators: [ [Object], [Object] ],
  tokenStandard: 4,
  collection: {
    verified: true,
    key: [PublicKey [PublicKey(CtsnQMdePUpQWrs4XEyG7qmtmAJb6FHaJDWqJx9w4SqC)]],
    address: [PublicKey [PublicKey(CtsnQMdePUpQWrs4XEyG7qmtmAJb6FHaJDWqJx9w4SqC)]]
  },
  collectionDetails: null,
  uses: null,
  programmableConfig: { __kind: 'V1', ruleSet: null }
}
```

Note the `address` (`6HuZcq6nWAGPmTpEfs2iRx6VE96o3hJsR5MHvyxnrPnr`) is actually the metadata PDA.

I may be wrong coz I find it very surprising if this has been broken in the SDK till now.

```
"@metaplex-foundation/js": "^0.18.3",
```
