### ISSUE TITLE
NftNotFoundError [MetaplexError]: NFT > NFT Not Found

### ISSUE THREAD

**Issue by stauersbol** [metaplex-foundation/js#292]
Hi,

So we are getting a error that has bugging us for a while.

```
2022-09-17T06:45:21.937Z		INFO	NftNotFoundError [MetaplexError]: NFT > NFT Not Found
>> Source: Plugin > NFT
>> Problem: No Metadata account could be found for the provided mint address: [4e8YRREPQU64hWfPnKRsuR3LKqqPR4Zy4ezZemWps7af].
>> Solution: Ensure the provided mint address is valid and that an associated Metadata account exists on the blockchain.
    at Object.handle (file:///var/task/node_modules/@metaplex-foundation/js/dist/esm/plugins/nftModule/findNftByMint.mjs:19:13)
    at runMicrotasks ()
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///var/task/node_modules/@metaplex-foundation/js/dist/esm/utils/Task.mjs:58:23
    at async Disposable.run (file:///var/task/node_modules/@metaplex-foundation/js/dist/esm/utils/Disposable.mjs:22:14)
    at async NftClient.create (file:///var/task/node_modules/@metaplex-foundation/js/dist/esm/plugins/nftModule/NftClient.mjs:49:17)
    at async handler (/var/task/.next/server/pages/api/mintNewNFT.js:159:9)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:184:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:403:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:493:37) {
  key: 'metaplex.errors.plugin.nft.nft_not_found',
  title: 'NFT > NFT Not Found',
  problem: 'No Metadata account could be found for the provided mint address: [4e8YRREPQU64hWfPnKRsuR3LKqqPR4Zy4ezZemWps7af].',
  solution: 'Ensure the provided mint address is valid and that an associated Metadata account exists on the blockchain.',
  source: 'plugin',
  sourceDetails: 'NFT',
  cause: undefined,
  logs: undefined
}
```

We found a issue that was previously made here, and we tried using that type of configuration on our endpoint.
We changed the default `confirmTransactionInitialTimeout` from 1min to 2min and have our commitment set to `finalized`.
We also have the same timeout setting for bundlrStorage. The mint address does exist when this error happens and it is showing on the chain.

Though for some reason this is still causing an issue for us, and we have no idea why this happens.

Is there any way this can be solved?

**Comment by lorisleiva** [comment]
Hi there 👋 

Is this happening whilst trying to create the NFT? Or are you just trying to fetch an existing NFT?

Trying to figure out if this is a race condition issue or something else.

**Comment by stauersbol** [comment]
This happening when I'm creating the NFT. The mint address you see point to an actual NFT that we create.

**Comment by stauersbol** [comment]
I can provide some code snippets a little later today, so you can see how we do it.

**Comment by lorisleiva** [comment]
Then I think this is a race condition issue. Meaning that we are trying to fetch the created NFT before the transaction has had the chance to finalize. It's on my To-Do list to improve this behaviour on the SDK but for now, you can fix this by adding the following parameter `{ confirmOptions: { commitment: "finalized" } }`.

I'll default to closing this but feel free to ask me to reopen if that doesn't fix your issue.
