### ISSUE TITLE
Receiving toArrayLike error when using auctionHouse list function

### ISSUE THREAD

**Issue by m4thfr34k** [metaplex-foundation/js#376]
Unable to utilize the  auctionHouse().list({}) or auctionHouse().builders().list({}) functions due to receiving toArrayLike error  

Steps to reproduce:  
  
Example repo which produces the error is located at https://github.com/m4thfr34k/metaplex-auction-list

```
  const auctionHouse = "Hvy8TQ6iuKmLQgWaEHBQksMMYAEH8aaPmD1pD2VMNToZ";
  const connection = new Connection(clusterApiUrl("mainnet-beta"));
  const metaplex = new Metaplex(connection);

  async function listItem() {
    const kinAuctionHouse = await metaplex.auctionHouse().findByAddress({
      address: new PublicKey(auctionHouse),
    });
    
    const listTransaction = metaplex
      .auctionHouse()
      .builders()
      .list({
        auctionHouse: kinAuctionHouse, 
        mintAccount: new PublicKey(
          "6e6XzDLpyxRF1zBxnx686bY8cwyVpmmZRgNJCte1VWrE"
        ),
        price: 15000000, 
        tokens: 1,
        printReceipt: true,
      });
  }
```
Error received is  
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toArrayLike')
    at AuctionHousePdasClient.tradeState (AuctionHousePdasClient.ts:131:1)
    at createListingBuilder (createListing.ts:332:1)
    at AuctionHouseBuildersClient.list (AuctionHouseBuildersClient.ts:100:1)
    at listItem (App.js:17:1)
```

Have tried with and without .builders() and received the same error.  

Am I doing something wrong here?  

Thank you for your time and assistance.

**Comment by lorisleiva** [comment]
Hi there 👋 

The `tokens` property must be of type `SplTokenAmount`.

```diff
+ import { token } from "@metaplex-foundation/js";

  const listTransaction = metaplex
    .auctionHouse()
    .builders()
    .list({
      auctionHouse: kinAuctionHouse, 
      mintAccount: new PublicKey(
        "6e6XzDLpyxRF1zBxnx686bY8cwyVpmmZRgNJCte1VWrE"
      ),
      price: 15000000, 
-     tokens: 1,
+     tokens: token(1),
      printReceipt: true,
    });
```

If your token uses decimals and a symbol then you can provide this information like this.

```ts
const tokens = token(5.43, 2, 'SMBL');
```
