### ISSUE TITLE
Error when trying to mint collection nft

### ISSUE THREAD

**Issue by fallenangel2305** [metaplex-foundation/js#416]
```
metaplex.nfts().create({
        name: "test",
        sellerFeeBasisPoints: 200,
        uri: "http://example.com/",
        isMutable: true,
        isCollection: true,
        collectionIsSized: true,
      }).then(nft => {
        console.log(nft, "test collection nft")
      })

```

ERROR
```
read-write.ts:28 Uncaught (in promise) AssertionError [ERR_ASSERTION]: We shouldn't ever need to resize, but 1 > 0
    at BeetWriter.maybeResize (read-write.ts:28:1)
    at BeetWriter.write (read-write.ts:38:1)
    at BeetWriter.writeStruct (read-write.ts:46:1)
    at BeetStruct.serialize (struct.ts:103:1)
    at FixableBeetArgsStruct.serialize (struct.fixable.ts:76:1)
    at createCreateMetadataAccountV3Instruction (CreateMetadataAccountV3.ts:78:1)
    at createSftBuilder (createSft.ts:444:1)
    at async createNftBuilder (createNft.ts:393:1)
    at async Object.handle (createNft.ts:280:1)
    at async Disposable.run (Disposable.ts:33:1)
```

**Comment by fallenangel2305** [comment]
```
import {
  clusterApiUrl,
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import { keypairIdentity, Metaplex, sol } from "@metaplex-foundation/js";
import Fs from "@supercharge/fs";

async function main() {

  const connection = new Connection(clusterApiUrl("mainnet-beta"));
  const metaplex = new Metaplex(connection);

  const collectionAuthority = Keypair.fromSecretKey(
    new Uint8Array(
      JSON.parse(
        //replace with actual path from home dir. For example '.config/solana/devnet.json'
        Fs.readFileSync(
          Fs.homeDir(
            ".config/solana/your_keypair.json"
          )
        ).toString()
      )
    )
  );

  // const collectionAuthority = Keypair.generate();

  metaplex.use(keypairIdentity(collectionAuthority));
  const { nft: collectionNft } = await metaplex.nfts().create({
    name: "My Collection NFT",
    uri: "https://example.com/path/to/some/json/metadata.json",
    sellerFeeBasisPoints: 0,
    isCollection: true,
    updateAuthority: collectionAuthority,
  });
  console.log(collectionNft.address.toBase58(), "collection nft address");
}
main();

```

this is a test in ts-node which works but when i try to create collection nft in react with javascript i get the above error
