### ISSUE TITLE
missing helpful error message for lack of funds

### ISSUE THREAD

**Issue by marionjmolnar** [metaplex-foundation/js#424]
hey👋 this is my first Github issue ever and i have 4 months of coding background so forgive me if i'm wrong in any way but i thought this might be useful to signal what could be a common error message that is missing

i got an intimidating, very long, error message when i tried to create a CandyMachine without having enough funds available

here it is (you can see in the logs at the end the problem is insufficient lamports)

```
      return new UnknownProgramError(program, error);
             ^

UnknownProgramError [MetaplexError]: SystemProgram > Unknown Program Error
>> Source: Program > SystemProgram [11111111111111111111111111111111]
>> Problem: The program [SystemProgram] at address [11111111111111111111111111111111] raised an error that is not recognized by the programs registered by the SDK.
>> Solution: Unfortunately, you will need to check the unparsed error below to investigate what went wrong. To get more helpful error messages, ensure the program that failed is registered by the SDK and provides an "errorResolver" method.

Caused By: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1

[ Logs: Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g invoke [1] |$> Program log: Instruction: Initialize |$> Program 11111111111111111111111111111111 invoke [2] |$> Program 11111111111111111111111111111111 success |$> Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g consumed 14928 of 800000 compute units |$> Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g success |$> Program 11111111111111111111111111111111 invoke [1] |$> Transfer: insufficient lamports 2255315080, need 3478816800 |$> Program 11111111111111111111111111111111 failed: custom program error: 0x1 ]

    at RpcClient.parseProgramError (file:///workspaces/codespaces-express/node_modules/@metaplex-foundation/js/dist/esm/plugins/rpcModule/RpcClient.mjs:247:14)
    at RpcClient.sendTransaction (file:///workspaces/codespaces-express/node_modules/@metaplex-foundation/js/dist/esm/plugins/rpcModule/RpcClient.mjs:75:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RpcClient.sendAndConfirmTransaction (file:///workspaces/codespaces-express/node_modules/@metaplex-foundation/js/dist/esm/plugins/rpcModule/RpcClient.mjs:105:23)
    ... 3 lines matching cause stack trace ...
    at async file:///workspaces/codespaces-express/metaplex.mjs:118:30 {
  key: 'metaplex.errors.program.unknown_program_error',
  title: 'SystemProgram > Unknown Program Error',
  problem: 'The program [SystemProgram] at address [11111111111111111111111111111111] raised an error that is not recognized by the programs registered by the SDK.',
  solution: 'Unfortunately, you will need to check the unparsed error below to investigate what went wrong. To get more helpful error messages, ensure the program that failed is registered by the SDK and provides an "errorResolver" method.',
  source: 'program',
  sourceDetails: 'SystemProgram [11111111111111111111111111111111]',
  cause: SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1
      at Connection.sendEncodedTransaction (/workspaces/codespaces-express/node_modules/@solana/web3.js/lib/index.cjs.js:7312:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Connection.sendRawTransaction (/workspaces/codespaces-express/node_modules/@solana/web3.js/lib/index.cjs.js:7269:20)
      at async RpcClient.sendTransaction (file:///workspaces/codespaces-express/node_modules/@metaplex-foundation/js/dist/esm/plugins/rpcModule/RpcClient.mjs:73:14)
      at async RpcClient.sendAndConfirmTransaction (file:///workspaces/codespaces-express/node_modules/@metaplex-foundation/js/dist/esm/plugins/rpcModule/RpcClient.mjs:105:23)
      at async TransactionBuilder.sendAndConfirm (file:///workspaces/codespaces-express/node_modules/@metaplex-foundation/js/dist/esm/utils/TransactionBuilder.mjs:136:22)
      at async Object.handle (file:///workspaces/codespaces-express/node_modules/@metaplex-foundation/js/dist/esm/plugins/candyMachineModule/operations/createCandyMachine.mjs:63:20)
      at async Disposable.run (file:///workspaces/codespaces-express/node_modules/@metaplex-foundation/js/dist/esm/utils/Disposable.mjs:22:14)
      at async file:///workspaces/codespaces-express/metaplex.mjs:118:30 {
    logs: [
      'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g invoke [1]',
      'Program log: Instruction: Initialize',
      'Program 11111111111111111111111111111111 invoke [2]',
      'Program 11111111111111111111111111111111 success',
      'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g consumed 14928 of 800000 compute units',
      'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g success',
      'Program 11111111111111111111111111111111 invoke [1]',
      'Transfer: insufficient lamports 2255315080, need 3478816800',
      'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
    ]
  },
  logs: [
    'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g invoke [1]',
    'Program log: Instruction: Initialize',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g consumed 14928 of 800000 compute units',
    'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g success',
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 2255315080, need 3478816800',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ],
  program: {
    name: 'SystemProgram',
    address: PublicKey {
      _bn: BN {
        negative: 0,
        words: [
          0, 0, 0, 0, 0,
          0, 0, 0, 0, 0,
          0
        ],
        length: 1,
        red: null
      }
    }
  }
}
```

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid this is what most errors look like in the Solana ecosystem at the moment haha.

The JS SDK tries to catch some of them and provide additional context but we can't do this for every single scenario.
