### ISSUE TITLE
not able to get list of nfts on react native

### ISSUE THREAD

**Issue by sandeep-myfriday** [metaplex-foundation/js#454]
i have an aync function to get the list of nfts for a wallet public key on a react native app but getting into an error as below

Possible Unhandled Promise Rejection (id: 0):
Error: URL.hostname is not implemented
Error: URL.hostname is not implemented
    at get (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:28902:24)
    at resolveClusterFromEndpoint (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:229777:35)
    at resolveClusterFromConnection (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:229774:38)
    at Metaplex (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:229744:123)
    at make (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:229756:24)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:228564:95)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:20735:26)
    at _next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:20754:29)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:20759:14)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:20751:25)
    at apply (native)
    at _showNfts (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.thursdaywallet&modulesOnly=false&runModule=true:228571:29)
    at apply (native)

Below is the piece of code i am working with

**async function showNfts() {
        const connection = new Connection(clusterApiUrl("devnet"));
        const wallet = Keypair.generate();

        const metaplex = Metaplex.make(connection)
            .use(keypairIdentity(wallet))
            .use(bundlrStorage());

        const owner = new PublicKey("2R4bHmSBHkHAskerTHE6GE1Fxbn31kaD5gHqpsPySVd7");
        const myNfts = await metaplex.nfts().findAllByOwner({
            owner: metaplex.identity().publicKey
        });
        //const allNFTs = await metaplex.nfts().findAllByOwner({owner: owner});

        console.log(myNfts);
    }**

**Comment by bryzettler** [comment]
@sandeep-myfriday any update on this? Currently hitting the same thing and not having luck resolving it

use the [react-native-url-polyfill](https://www.npmjs.com/package/react-native-url-polyfill) package
