### ISSUE TITLE
Metaplex 0.18.0: Program [TokenMetadataProgram] raised an error that is not recognized by the programs registered on the SDK.

### ISSUE THREAD

**Issue by mikemaccana** [metaplex-foundation/js#463]
The following code works perfectly on metaplex 0.15.0:

    let createOutput = await metaplexNFTs.create({
      uri: uploadResponse.uri, // "https://arweave.net/123",
      name: IDENTITY_TOKEN_NAME,
      sellerFeeBasisPoints: 0, // 500 would represent 5.00%.
    });
  
  (original code also has `.run()` which I understand is no longer necessary and have removed)
    
  However I'd like to move to a newer and better supported metaplex release. In Metaplex 0.18.0 the code gives the following output:
  
  ```
  UnknownProgramError: The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error that is not recognized by the programs registered on the SDK. Please check the underlying program error below for more details.

    Source: Program > TokenMetadataProgram [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s]

    Caused By: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Failed to serialize or deserialize account data: Unknown

    Program Logs:
    | Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
    | Program log: Error: BorshIoError
    | Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 3412 of 400000 compute units
    | Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Failed to serialize or deserialize account data: Unknown

      74 |   let createOutput: CreateNftOutput;
      75 |   try {
    > 76 |     createOutput = await metaplexNFTs.create({
         |                    ^
      77 |       uri: uploadResponse.uri, // "https://arweave.net/123",
      78 |       name: IDENTITY_TOKEN_NAME,
      79 |       sellerFeeBasisPoints: 0, // 500 would represent 5.00%.

      at RpcClient.parseProgramError (node_modules/@metaplex-foundation/js/src/plugins/rpcModule/RpcClient.ts:367:9)
      at RpcClient.sendTransaction (node_modules/@metaplex-foundation/js/src/plugins/rpcModule/RpcClient.ts:128:18)
      at async RpcClient.sendAndConfirmTransaction (node_modules/@metaplex-foundation/js/src/plugins/rpcModule/RpcClient.ts:164:23)
      at async TransactionBuilder.sendAndConfirm (node_modules/@metaplex-foundation/js/src/utils/TransactionBuilder.ts:197:22)
      at async Object.handle (node_modules/@metaplex-foundation/js/src/plugins/nftModule/operations/createNft.ts:333:20)
      at async Disposable.run (node_modules/@metaplex-foundation/js/src/utils/Disposable.ts:33:14)
      at async mintToken (src/backend/minting-tokens.ts:76:20)
  
  ```

By the way, it's quite possible I've missed something I need to do after a Metaplex upgrade - I can't find a `CHANGELOG` or release notes for Metaplex anywhere. If I've missed them sorry about that, please let me know where they are!

**Comment by mikemaccana** [comment]
I think I needed to upgrade metaplex on my local validator. Still getting errors, but different errors. Closing.
