### ISSUE TITLE
TypeError: bundlrStorage is not a function

### ISSUE THREAD

**Issue by NetGodFather** [metaplex-foundation/js#547]
```
const web3 = require('@solana/web3.js');
const { Metaplex, keypairIdentity, bundlrStorage } = require('@metaplex-foundation/js');

const connection = new web3.Connection(web3.clusterApiUrl('devnet'));
const wallet = web3.Keypair.generate();

async function createNFT() {
    const metaplex = Metaplex.make(connection)
        .use(keypairIdentity(wallet))
        .use(bundlrStorage());

    const { nft } = await metaplex.nfts().create({
        uri: 'https://example.com/my-nft-metadata.json',
        name: 'My NFT',
        sellerFeeBasisPoints: 500, // 5%
    }).run();

    console.log(nft);
}

createNFT().catch(console.error);
```

Error reported:

```
TypeError: bundlrStorage is not a function
    at createNFT (/Users/tallone/Documents/Umi/index.js:10:14)
    at Object.<anonymous> (/Users/tallone/Documents/Umi/index.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49
```

**Comment by Superlukec** [comment]
@bundlr-network/client@0.8.9: Bundlr is now Irys - please switch to @irys/sdk - this package will remain compatible with Irys for the foreseeable future.


Meanwhile you can just change the version:
` npm i @metaplex-foundation/js@0.18.3`

**Comment by Superlukec** [comment]
```
import { Metaplex, keypairIdentity, toMetaplexFile, toBigNumber, irysStorage } from "@metaplex-foundation/js";

const METAPLEX = Metaplex.make(SOLANA_CONNECTION)
    .use(keypairIdentity(WALLET))
    .use(irysStorage({
        address: 'https://devnet.irys.xyz',
        providerUrl: QUICKNODE_RPC,
        timeout: 120000,
 }));
```

**Comment by anisurrahman072** [comment]
Use **irysStorage** instead of **bundlrStorage**
