### ISSUE TITLE
Failed to load metaplex

### ISSUE THREAD

**Issue by georgewslee** [metaplex-foundation/js#553]
I have a file named testMetaplex.cjs with just one line of code:
const Metaplex = require("@metaplex-foundation/js");
Running on Node.js v20.15.0.

my npm list:
├── @metaplex-foundation/js@0.20.1
├── @raydium-io/raydium-sdk@1.3.1-beta.57
├── @solana/spl-token-registry@0.2.4574
├── @solana/spl-token@0.4.7
└── @solana/web3.js@1.93.4

and I get the following error:
...\node_modules\@metaplex-foundation\mpl-candy-guard\dist\src\generated\instructions\mint.js:27
const splToken = __importStar(require("@solana/spl-token"));

Error [ERR_REQUIRE_ESM]: require() of ES Module ...\node_modules\@solana\spl-token\lib\cjs\index.js from ...\node_modules\@metaplex-foundation\mpl-candy-guard\dist\src\generated\instructions\mint.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in ...\node_modules\@solana\spl-token\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (...\node_modules\@metaplex-foundation\mpl-candy-guard\dist\src\generated\instructions\mint.js:27:31) {
  code: 'ERR_REQUIRE_ESM'
}

Is it possible to use metaplex via cjs?

**Comment by FilipeAleixo** [comment]
Same issue on Mac M3.

node 18.9.1, pnpm 8.8.0

Forcing @solana/spl-token to version 0.4.6 solved my issue. on pnpm-lock.yaml it set that package to 0.4.7 when I did a fresh install and it broke.

**Comment by youngqqcn** [comment]
same issue  with `0.4.7`

```
"dependencies": {
    "@solana/spl-token": "^0.4.7",
    "@solana/web3.js": "^1.94.0",
    "@types/node": "^20.14.9",
    "tslint": "^6.1.3",
    "typescript": "^5.5.3"
  },
```


```
/usr/lib/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/yqq/fansland/fansland_ai/demos/spl-token-use/node_modules/@solana/spl-token/lib/cjs/index.js from /home/yqq/fansland/fansland_ai/demos/spl-token-use/src/index.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/yqq/fansland/fansland_ai/demos/spl-token-use/node_modules/@solana/spl-token/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at require.extensions.<computed> [as .js] (/usr/lib/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/home/yqq/fansland/fansland_ai/demos/spl-token-use/src/index.ts:3:21)
    at m._compile (/usr/lib/node_modules/ts-node/dist/index.js:857:29) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
```

**Comment by ordas21** [comment]
same issue for me

**Comment by georgewslee** [comment]
> I have a file named testMetaplex.cjs with just one line of code: const Metaplex = require("@metaplex-foundation/js"); Running on Node.js v20.15.0.
> 
> my npm list: ├── @metaplex-foundation/js@0.20.1 ├── @raydium-io/raydium-sdk@1.3.1-beta.57 ├── @solana/spl-token-registry@0.2.4574 ├── @solana/spl-token@0.4.7 └── @solana/web3.js@1.93.4
> 
> and I get the following error: ...\node_modules@metaplex-foundation\mpl-candy-guard\dist\src\generated\instructions\mint.js:27 const splToken = __importStar(require("@solana/spl-token"));
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module ...\node_modules@solana\spl-token\lib\cjs\index.js from ...\node_modules@metaplex-foundation\mpl-candy-guard\dist\src\generated\instructions\mint.js not supported. index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules. Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in ...\node_modules@solana\spl-token\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
> 
> ```
> at Object.<anonymous> (...\node_modules\@metaplex-foundation\mpl-candy-guard\dist\src\generated\instructions\mint.js:27:31) {
> ```
> 
> code: 'ERR_REQUIRE_ESM' }
> 
> Is it possible to use metaplex via cjs?

I ended up using @metaplex-foundation/umi-bundle-defaults and @metaplex-foundation/mpl-token-metadata instead.
My intention was just to get token metadata, given a token address.
